---
title: "Data EDA"
author: "P. Wittel"
date: "4/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

train_balance <- add_id(train) %>% calculate_balance(.)

```

```{r}

ggplot(data = train_balance) +
  geom_boxplot(mapping = aes(y = default, x = age))

ggplot(data = train_balance) +
  geom_bar(mapping = aes(x = default, fill = education), position = "fill")

ggplot(data = train_balance) +
  geom_bar(mapping = aes(x = default, fill = sex), position = "fill")

ggplot(data = train_balance) +
  geom_bar(mapping = aes(x = default, fill = marriage), position = "fill")

```


There is not a strong difference between the two levels 

```{r}

train_balance %>% 
  crossRow_pay_avg() %>% 
  ggplot(.) +
  geom_violin(aes(x = pay_amt_avg, y = default))

train_balance %>% 
  crossRow_bill_avg() %>% 
  ggplot(.) +
  geom_violin(aes(x = bill_amt_avg, y = default))


train_balance %>% 
  crossRow_balance_avg() %>% 
  ggplot(.) +
  geom_violin(aes(x = balance_amt_avg, y = default))


```

```{r}

ggplot(train_balance) +
  geom_violin(aes(x = limit_bal, y = default))

```